import { headDesignPlanDirection, usesSpeciesHead, type CharacterDesignContext } from "./character-design";

// Original treatment informed by transcripts and the user's visual references.
export const TELENOVELA_STYLE = "Telenovela 3D expresiva";

export const TELENOVELA_DESCRIPTION =
  "Personajes humanoides atractivos y expresivos, moda cotidiana actual y cabello cuidados, acabado 3D orgánico. Rasgos de fruta o gema integrados en cabeza y piel. Diálogos directos, según el género y el cierre que elijas.";

export function visualTreatment(style: string, context?: CharacterDesignContext): string {
  return [
    `ESTILO ÚNICO DEL UNIVERSO: ${style}. Es obligatorio en personajes, escenarios, objetos, tomas y videos, también en capítulos siguientes.`,
    "La misma técnica, grado de estilización, diseño facial y acabado de materiales se mantienen en todo el reparto. No mezclar 2D, 3D, fotografía ni estilos de otros universos. Cambiar de generador no cambia el estilo. El tono de la historia modifica la actuación y la luz de una escena, no la técnica de animación. Los rasgos individuales distinguen personajes sin cambiar la dirección artística. Si una ficha heredada sugiere otra técnica, conserva su identidad física y represéntala con el estilo elegido aquí.",
    "DISEÑO HUMANOIDE DEL REPARTO: al crear personajes de frutas, alimentos, cristal, diamantes o minerales, diseña personas de anatomía humanoide estilizada: cabeza, cuello, hombros, torso, cintura, brazos de anatomía natural, manos, piernas y pies con proporciones coherentes con su edad. Rostros hermosos y armoniosos, ojos expresivos, cejas, nariz y labios modelados; siluetas cuidadas y vestuario que se adapta al cuerpo. Cabello peinado cuando corresponda al diseño. La arquitectura de la cabeza la gobierna el selector Diseño del personaje cuando esa categoría lo admite: modo Humanoide conserva cabeza/rostro humanoides; modo Cabeza de especie/material usa una cabeza completa reconocible de la especie/material con proporciones adultas estables y rostro expresivo integrado. El selector también gobierna la corona de la cabeza: en modo de especie/material son válidos hojas, cáliz, tallo, facetas o su acabado natural, sin cabello humano obligatorio; en Humanoide conserva cabello humanoide. El torso y las extremidades están diseñados como un cuerpo, no como una fruta entera con bracitos pegados. Nada de recortes fotográficos de fruta, extremidades de palitos, muñecos toscos o mezcla de fotografía y dibujo. Belleza y acabado cuidado también en personajes pobres o antagonistas; expresar su situación con actuación y vestuario, sin volverlos grotescos por defecto. Conserva diferencias de edad, personalidad y complexión. En personajes YA aprobados conserva su identidad y anatomía: cambiar una ficha existente requiere regenerarla, no rediseñarla silenciosamente entre tomas.",
    "DISEÑO DE MUJERES ADULTAS: belleza idealizada de protagonista de animación, rostro armonioso, ojos expresivos, pestañas definidas, labios bien dibujados o modelados según la técnica y expresiones atractivas. Cuerpo humanoide inequívocamente adulto, voluptuoso e idealizado: curvas naturales y proporcionadas, cintura definida de anchura anatómicamente creíble, busto lleno proporcionado al tórax, caderas amplias integradas suavemente en la pelvis, glúteos redondeados, muslos torneados, piernas largas y manos cuidadas. Transiciones suaves entre costillas, abdomen y caderas, sin cintura pinzada ni estrechamiento extremo, sin formas geométricas rígidas. Mantén equilibrio anatómico, articulaciones naturales y continuidad entre torso y extremidades; sin deformaciones ni proporciones imposibles. Estas características corporales son obligatorias en todos los estilos visuales, incluido 2D, anime, 3D, cinematográfico y realista: cambia la técnica de representación, no la silueta. Silueta glamorosa de protagonista, postura elegante y anatomía continua y bien resuelta; no aspecto infantil ni cuerpo esférico de fruta. Vestuario favorecedor, bien ajustado y coherente con el papel y la escena: vestidos, pantalones, ropa cotidiana o uniforme según la historia. Conservar exactamente estas proporciones entre referencias y tomas. Esta pauta de figura adulta se aplica solo a mujeres adultas; los personajes de otras edades conservan proporciones de su edad.",
    "TIPO DE SERES — REGLA GLOBAL DURA: la selección del usuario gobierna TODO el reparto, sin excepciones inventadas por el Director. Frutas = cuerpo humanoide, cabeza gobernada por el selector y PIEL DE FRUTA NATURAL orgánica y viva, de microtextura reconocible; Verduras = piel/material vegetal natural; Diamantes y minerales = superficie mineral/cristalina; Humanos = piel y rasgos humanos, sin materiales de otros tipos; Animales = naturaleza animal visible; Objetos = material/diseño del objeto; Robots = construcción robótica visible; Antropomorfos = naturaleza no humana integrada a anatomía humanoide; Insectos = rasgos/material de insecto; Ángeles = rasgos angelicales del universo. Nunca convertir a un hombre, anciano, autoridad, antagonista o secundario en humano solo por su papel cuando el tipo global no sea Humanos. La ficha individual define identidad, edad, género, vestuario y especie concreta dentro de la familia, pero NO puede cambiar la familia global. Todos comparten acabado cuidado y coherente con el estilo visual elegido.",
    "COHERENCIA DE FAMILIA: si se eligen Humanos, todos son humanos salvo una excepción escrita explícitamente por el usuario; la misma regla global se aplica a cada familia seleccionada.",
    "Los hombres adultos también tienen rostros armoniosos, expresivos y coherentes con la misma dirección artística del reparto; edad, profesión o rol no reducen la calidad visual.",
    usesSpeciesHead(context)
      ? "CORONA DEL REPARTO: conserva el cáliz, hojas, tallo, facetas, antenas o remate propio de cada especie/material. El cabello humano es opcional, no una condición de belleza. Si la ficha aprobada incluye cabello, respétalo sin ocultar el volumen y contorno reconocible de la cabeza completa. Una ficha sin cabello humano no necesita una peluca añadida."
      : "CABELLO DEL REPARTO: los seres humanoides de fruta, diamante, cristal, mineral y demás materiales llevan cabello humanoide visible, hermoso, con volumen y caída natural, además de sus rasgos de especie. El material del cuerpo define la piel y la cabeza, no obliga a ser calvo. Varía entre personajes cabelleras rubias, negras, castañas y pelirrojas; peinados cortos y largos, lisos, ondulados y rizados. Conserva el color y peinado definidos en la ficha y en la referencia aprobada en todas las imágenes y clips. En retratos antiguos cuya ficha diga 'No aplica' o 'No tiene' solo por ser fruta o gema, aplica el peinado estable designado para el personaje al regenerarlo; no transfieras el cabello de otro personaje de la referencia editorial.",
    "IDENTIDAD ESTABLE: gender y age de la ficha son parte de la identidad, al igual que especie, rostro y cabello. Conservarlos en todos los estilos, referencias, escenas y capítulos. Respetar mujeres, hombres y otras identidades según la historia; no decidirlos por el nombre de una fruta, profesión, ropa o personalidad. Una referencia de acabado de otro personaje nunca transfiere su género, edad, especie ni facciones.",
    "GLAMOUR VISUAL RECURRENTE: en personajes adultos, mantener una presentación atractiva y carismática como parte estable de Universos IA. Usar vestuario favorecedor coherente con la situación, siluetas cuidadas, postura segura, poses naturales, miradas expresivas, química visual entre personajes, proximidad y composición vertical que destaque su presencia cuando la escena lo permita. En romance, celos o tensión interpersonal, reforzar esa química mediante miradas, lenguaje corporal y cercanía sin abandonar la acción narrativa. Esta dirección se aplica automáticamente y no necesita aparecer en el concepto del usuario.",
    headDesignPlanDirection(context),
    "COLOR Y LEGIBILIDAD DEL REPARTO: colores vivos, limpios y ricos propios de cada personaje. Rostros y cuerpos claramente iluminados y separados del fondo incluso al atardecer o en interiores; usar luz de relleno suave sin borrar el volumen. No subexponer protagonistas para destacar ventanas, mobiliario o fondos. Mantener acabado cuidado y atractivo, con brillo controlado donde corresponda al material y a la técnica; en 2D expresar estos valores mediante color y sombreado dibujados, nunca forzar render 3D.",
    "UNIDAD ARTÍSTICA PERSONAJE–ESCENARIO: personajes, vegetación, arquitectura, vehículos, muebles, objetos y fondo deben parecer renderizados por el MISMO estudio, motor y película. En estilos 3D, el escenario también es 3D estilizado con la misma simplificación de formas, materiales, microtextura, iluminación, profundidad y tratamiento de color de los personajes. No colocar personajes de animación sobre jardines, calles, habitaciones, plantas o cielos fotorrealistas. No usar fotografía ni fondos de apariencia fotográfica detrás de personajes 3D. A la inversa, tampoco convertir personajes en muñecos de plástico, resina, vinilo, plastilina o figuras coleccionables. Piel/superficie viva con variación sutil, ropa con tejido y pliegues, cabello con hebras/volumen; entorno con materiales estilizados compatibles y detalle controlado. La imagen completa debe leerse como un único fotograma de la misma producción.",
    "ANATOMÍA CONTINUA: representar personajes vivos, con piel o superficie corporal continua sobre hombros, codos, muñecas, caderas, rodillas y tobillos. Las articulaciones se flexionan mediante anatomía natural y pliegues suaves, sin piezas separadas, ranuras circulares, bisagras, rótulas de juguete, costuras de ensamblaje ni acabado de muñeca de plástico o maniquí. En frutas y humanos la piel es flexible; en gemas el material conserva continuidad visual. Solo los robots u objetos mecánicos explícitamente elegidos pueden mostrar uniones mecánicas propias de su diseño.",
    specificTreatment(style),
  ].join("\n");
}

export function specificTreatment(style: string): string {
  if (style === "Anime 2D" || style === "Anime") return "ANIME 2D CINEMATOGRÁFICO: animación japonesa 2D de alta calidad, fondos pintados ricos, luz atmosférica, composición cinematográfica, contornos limpios, sombras cel refinadas, color profundo y movimiento expresivo. Personajes, fondos y objetos comparten acabado dibujado y el mismo lenguaje de línea. Rostros expresivos de anime, anatomía consistente y movimiento animado 2D. Sin modelado volumétrico 3D, render de juguete ni fotografía.";
  if (style === "Animación 2D") return "ANIMACIÓN 2D: caricatura bidimensional dibujada, siluetas claras, contorno de grosor coherente, paleta consistente y sombras planas sencillas. Todo el reparto y los fondos pertenecen al mismo dibujo animado. Actuación expresiva en 2D, sin render 3D, volumen fotográfico ni texturas fotorrealistas.";
  if (style === "Realista") return "REALISTA: acabado fotorrealista coherente en personajes, escenarios y objetos; materiales, microtexturas, óptica y luz físicamente plausibles. Los seres fantásticos o frutas antropomorfas conservan la anatomía aprobada, representada de forma realista. Sin ojos de caricatura añadidos, proporciones chibi, contornos dibujados ni sombreado cel. La fantasía del ser no cambia la técnica visual.";
  if (style === "Ilustración animada") return "ILUSTRACIÓN ANIMADA 2D: ilustración digital pintada de formas planas, pincelada suave y textura pictórica uniforme en personajes y fondos. Contornos discretos, capas bidimensionales y movimientos suaves que conservan el dibujo. Sin convertir la imagen en modelado 3D, fotografía o anime cel. Mantener el mismo trazo, paleta y acabado pictórico en cada referencia y toma.";
  if (style === "Animación 3D familiar (tipo Pixar)") return "ANIMACIÓN 3D FAMILIAR: formas redondeadas y orgánicas, siluetas atractivas, ojos grandes expresivos, boca articulada, piel viva de textura sutil, ropa de tela con pliegues, luz suave y color rico. Personajes, escenarios y objetos comparten el acabado de un largometraje familiar de animación 3D. Actuación emocional clara, movimientos fluidos y peso corporal creíble. Diseños originales, sin copiar personajes existentes. Sin superficie de juguete, fotografía, acabado de terror hiperrealista, dibujo 2D ni anime cel. El acabado visual no cambia el género ni el público elegido.";
  if (style === "3D Viral Estilizado") return [
    "DIRECCIÓN VISUAL: 3D VIRAL ESTILIZADO.",
    "Animación 3D estilizada vertical, colorida y muy expresiva: personajes adultos atractivos, ojos grandes legibles, rostros expresivos hermosos integrados en la cabeza elegida, cabello o corona natural según ese diseño, siluetas claras y actuación facial inmediata. Volumen 3D evidente pero deliberadamente NO fotorrealista; superficies orgánicas suaves con variación, ropa con tejido y pliegues, sin plástico, resina, vinilo ni plastilina.",
    "ESCENARIOS DEL MISMO UNIVERSO: arquitectura, restaurantes, baños, dormitorios, calles, clubes, vehículos, plantas, muebles, cielos y objetos usan geometría 3D estilizada, color rico, detalle simplificado, iluminación cinematográfica coherente con la localización y profundidad limpia. Nunca fotografía, jardín fotorrealista ni fondo real detrás de personajes animados. NO usar neón como firma visual del estilo: el neón solo aparece cuando el mundo seleccionado o una fuente concreta de la escena lo exige.",
    "COMPOSICIÓN PARA VIDEO CORTO: lectura instantánea en 9:16, protagonista dominante, expresiones claras, poses naturales, química visual, contraste de color y fondos suficientemente detallados para situar la acción sin competir con el reparto.",
    "El cuerpo mantiene anatomía humanoide proporcionada. La cabeza de Frutas, Verduras, Diamantes/minerales, Objetos e Insectos sigue el selector Diseño del personaje; el estilo 3D no puede cambiar esa elección. La corona natural o el cabello que realmente tenga cada ficha aprobada se conserva sin imponer pelo humano en el modo de cabeza de especie/material.",
  ].join("\n");
  if (style === "Cinemático Épico" || style === "Cinemático 3D") return [
    "DIRECCIÓN VISUAL COMPARTIDA: CINEMÁTICO ÉPICO.",
    "Tratamiento de gran superproducción cinematográfica: escala épica, composición de largometraje, iluminación dramática de alto presupuesto, profundidad atmosférica, lentes y cámara cinematográficas, escenarios monumentales cuando la historia lo justifique. Personajes y escenarios pertenecen a la misma película. No confundir con el 3D viral estilizado ni con fotografía casual. Todos los personajes y escenarios pertenecen a la misma película de animación 3D estilizada. Rostros de animación con ojos grandes legibles, mejillas suaves y expresiones claras, proporción adulta estilizada pero estable, con cabeza expresiva de escala anatómicamente coherente respecto al cuerpo. Cuando el tipo global sea Frutas: piel inequívocamente frutal, viva y flexible, con pigmentación rica, microtextura orgánica de cáscara/pulpa suficientemente visible para reconocer el material, poros/fibras/moteado fino y variación tonal; reflejos anchos y suaves. Debe leerse como materia de fruta viva, NO como piel humana simplemente teñida ni como plástico, resina, vinilo, cera o laca. Cuando el tipo sea otro, usa su material correspondiente; ropa de tela con pliegues y costuras visibles. Anatomía continua con volumen natural en cuello, hombros, codos y rodillas; una pose espontánea con el peso apoyado en una pierna y expresión de un instante real. Iluminación cálida modelada, sombras coherentes y una única calidad de render. Evita la superficie brillante homogénea de resina, la piel lisa de plastilina y la postura simétrica de maniquí. Mantén el mismo grado de estilización, detalle y tratamiento de ojos, boca y superficies para todo el reparto. Las diferencias de especie, edad y vestuario no cambian la técnica de render ni convierten a un personaje en dibujo plano, muñeco de otra película o fotografía realista.",
    "Respeta la anatomía, proporciones individuales, materiales, colores y rasgos aprobados. El género y el papel del personaje afectan su actuación y vestuario, no cambian por sí solos el estilo gráfico. En referencias canónicas usa luz neutra legible para documentar los colores reales; reserva la iluminación dramática del escenario para las tomas narrativas.",
  ].join("\n");
  if (style !== TELENOVELA_STYLE) return "";
  return [
    "TRATAMIENTO VISUAL: TELENOVELA 3D EXPRESIVA.",
    "ACABADO DE LAS REFERENCIAS: cuerpo humanoide adulto completo; la cabeza de cada fruta sigue exclusivamente el selector (Humanoide o Cabeza de especie/material), sin cambiarlo por elegir este estilo; para Humanos, cabeza y piel humanas, sin rasgos de fruta. La piel de cara, cuello, brazos y piernas mantiene el color y material del tipo elegido con reflejos pulidos, suaves y controlados. En Humanoide conserva el cabello humanoide de la ficha; en Cabeza de especie/material conserva la corona natural o el cabello opcional elegido. Las hojas, tallos, cáliz o facetas pueden sustituir al pelo y deben dejar reconocible la silueta completa de la especie. Ropa con costuras y caída creíble, accesorios definidos y escenarios 3D detallados con luz cálida o natural según la escena. Los hombres pueden tener complexiones distintas, incluida robusta, sin cambiar el acabado común. No añadir marcas, logos, números de dinero o contadores en la frente tomados de las referencias.",
    "Animación 3D de telenovela con protagonistas humanoides hermosos, proporciones elegantes, rostros expresivos y acabado de largometraje pulido. Modelado continuo de cabeza, cuello, torso y extremidades; manos anatómicas estilizadas, ropa bien confeccionada y cabello con volumen y peinado definido cuando corresponda. Ojos grandes con párpados y pestañas, cejas articuladas, nariz y labios esculpidos. Materiales suaves y detallados, iluminación cálida y clara, colores ricos, volumen consistente. Escenarios cotidianos reconocibles; actuación teatral legible sin deformar la identidad. No convertir a todo el reparto en bebés cabezones ni en criaturas de terror.",
    "Respeta el tipo de seres elegido y las fichas aprobadas. En frutas integra su identidad en la cabeza y la piel del cuerpo humanoide: por ejemplo semillas y color propios de la especie, hojas como detalle de la cabeza. El cuerpo lleva ropa y tiene torso y extremidades proporcionados; no es una fruta fotografiada a la que se añaden brazos. En diamantes y minerales conserva facetas, reflejos y el material de cada personaje; no les añadas piel de fruta. Los demás tipos de seres conservan su propia identidad. No mezcles especies por aplicar este estilo.",
    "Planos medios y primeros planos para diálogo y reacción, con planos abiertos solo cuando expliquen una acción. Composición vertical, separación clara entre personajes y fondo. Movimiento corporal expresivo y sincronización de boca con el diálogo aprobado. No introducir movimientos de cámara que oculten la acción. Mantener exactamente vestuario, proporciones, colores y voces aprobados. No añadir rótulos, marcas de canal ni personajes de referencia.",
  ].join("\n");
}

export function endingDirection(ending: string): string {
  if (ending === "Cliffhanger")
    return "CIERRE ELEGIDO — CLIFFHANGER: la decisión o intento de solución del protagonista provoca una consecuencia visible que abre una pregunta concreta para el siguiente capítulo. El espectador entiende qué está en juego y qué resultado falta conocer. Termina en ese descubrimiento o dilema, antes de resolverlo; no cortes una frase a medias, no uses una amenaza vaga ni añadas Continuará como sustituto de la historia. La consecuencia debe nacer de lo mostrado antes.";
  if (ending === "Giro final")
    return "CIERRE ELEGIDO — GIRO FINAL: una revelación visible, preparada por una pista anterior, cambia el significado de lo sucedido. Muestra la reacción o consecuencia inmediata para que el giro se entienda; no lo sustituyas por una pregunta sin respuesta.";
  return "CIERRE ELEGIDO — RESOLUCIÓN: muestra el resultado de la decisión y resuelve el conflicto principal de este capítulo con una consecuencia comprensible. Respeta el cierre aprobado; no impongas un cliffhanger por tratarse de un video corto.";
}

export function narrativeTreatment(style: string, context?: CharacterDesignContext): string {
  return [
    visualTreatment(style, context),
    "RITMO NARRATIVO DE TELENOVELA BREVE: aplica este tratamiento respetando género, subgénero, trama, tono, idioma, acento y cierre seleccionados; no impongas romance, violencia ni humor si no corresponden.",
    "Abre dentro de un conflicto concreto mostrando también su causa legible: el rasgo, regla o hecho visible que provoca la primera reacción social. Protagonista con un deseo claro y otro personaje que lo dificulta. Permite que la incomodidad y la frustración motiven la decisión posterior; no sustituyas el planteamiento por la escena de la solución. Usa lenguaje cotidiano y diálogo corto de acción y respuesta; cada intervención cambia la situación. Evita prólogos explicativos, metáforas rebuscadas y narración que repita lo que ya se ve.",
    "Construye una sola cadena de causa y consecuencia en 64 segundos: arranque que engancha, obstáculo, decisión, consecuencia y cierre elegido. Pocos personajes y lugares. No comprimas una temporada completa en un capítulo. Un giro nace de una pista anterior; resolución cierra el conflicto del capítulo, giro final lo reinterpreta y final en suspenso deja una pregunta concreta. La continuación conserva la misma historia y el estado final anterior.",
    "MOTOR CONCRETO DE LA HISTORIA: el público debe entender pronto qué quiere el protagonista, qué hecho visible se lo impide y qué puede perder o ganar. La presión lo lleva a intentar una solución y ese intento produce una consecuencia que obliga a reaccionar. La emoción acompaña esa cadena, no la sustituye. Una conversación puede ocupar varios clips, pero una réplica cambia información, poder, expectativa o decisión; varias miradas, caricias o declaraciones equivalentes no son progresión. Pocos hechos claros tienen más fuerza que secretos, listas, reglas o relaciones cuyo significado nadie explica mediante la acción.",
    "HISTORIA QUE REALMENTE SE PRODUCE: formula premisa, conflicto, arco y cierre a partir de momentos que puedan verse u oírse en los 64 segundos. Cada hecho indispensable prometido al usuario debe tener una acción visible o una intervención concreta en el plan. No vendas una sinopsis de gran aventura y después filmes solo una conversación estática; tampoco conviertas estados internos como se debate entre dos amores en toda la acción. Reduce la premisa a lo que sí puede producirse con pocas personas, acciones simples y las tomas disponibles. En el plan conserva la historia aprobada y materializa sus hechos esenciales; no inventes otra trama para darle ritmo.",
    "Las frutas y gemas viven conflictos humanos comprensibles. Sus materiales dan identidad visual y, cuando sea útil, una consecuencia narrativa sencilla; no inventes leyes biológicas complicadas como requisito para contar la historia. Crea nombres, escenas y diálogos originales, sin reproducir argumentos de los ejemplos.",
    "En propuestas entrega tres alternativas breves independientes. Tras la elección desarrolla únicamente la elegida. En el plan reparte el capítulo en ocho clips de ocho segundos, con frases que quepan y reacciones causales que ocupen hasta el final del clip; no abras cada clip con una nueva introducción. Estas pautas se incorporan en las llamadas existentes, sin revisiones adicionales de estilo.",
    "PUESTA EN ESCENA: en el plan prioriza diálogo y reacción visibles. Varía planos de dos personajes, planos medios, primeros planos individuales o detalles de objetos ENTRE clips, solo cuando el reparto y la acción lo permitan. Cada clip tiene su propia imagen inicial y una única toma continua de ocho segundos; no pidas contraplano, insertos ni rostros nuevos dentro del mismo video. En un diálogo compartido mantén visibles a todos sus participantes; un primer plano de un solo personaje requiere un clip propio con ese reparto. Mantén el eje de miradas, posiciones, manos y objetos entre cortes. Durante una intervención usa cejas, boca, mirada y gestos de manos; quien escucha también reacciona. Cámara estable o acercamiento suave, sin moverla sin propósito ni encadenar cortes que impidan entender el conflicto. Una acción principal clara por clip y tiempo para que se lea la emoción.",
  ].join("\n");
}
